version: 1.0.{build}
image: Visual Studio 2017

configuration: Release

before_build:
- cmd: >-
    nuget restore

build:
  project: eWolfPixels.sln
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false
  verbosity: minimal

  test_script:
  - cmd: dotnet test
  - cmd: dotnet test "C:\projects\eWolfPixel\Pixel\eWolfPixelStandard.UnitTests\eWolfPixelStandard.UnitTests.csproj" --no-build --logger:Appveyor
